spring.application.name=mcp-client-example
spring.main.web-application-type=none
spring.threads.virtual.enabled=true
spring.profiles.active=ollama
spring.docker.compose.file=./mcp-example/mcp-client-example/database-compose.yaml
spring.ai.model.embedding=none
spring.ai.model.moderation=none
spring.ai.model.ocr=none
spring.ai.chat.memory.repository.jdbc.initialize-schema=always
spring.ai.mcp.client.streamable-http.connections.pope-search-mcp-server.url=http://localhost:8080/mcp
spring.ai.mcp.client.streamable-http.connections.time-mcp-server.url=http://localhost:8081/mcp
logging.level.org.springframework.ai.chat.client.advisor=DEBUG
