<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.1.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.1.0 http://maven.apache.org/xsd/maven-4.1.0.xsd">
    <modelVersion>4.1.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.1.1</version>
        <relativePath/>
    </parent>
    <groupId>com.github.nicolaskrier.experimental</groupId>
    <artifactId>spring-ai-examples</artifactId>
    <packaging>pom</packaging>
    <version>0.0.1-SNAPSHOT</version>
    <properties>
        <java.version>25</java.version>
        <!-- TODO: Use a release version once GH-6974 and GH-6977 fixes are available. -->
        <spring-ai.version>2.0.2-SNAPSHOT</spring-ai.version>
        <!-- TODO: Use an Arconia version aligned with Spring AI and Spring Boot versions. -->
        <arconia.version>0.30.0</arconia.version>
        <!-- This version is compatible with OpenTelemetry 1.62.0 version used by Spring Boot. -->
        <opentelemetry-logback-appender.version>2.28.1-alpha</opentelemetry-logback-appender.version>
    </properties>
    <subprojects>
        <subproject>chat-client-example</subproject>
        <subproject>chat-model-example</subproject>
        <subproject>mcp-example</subproject>
        <subproject>mistral-ai-api-example</subproject>
        <subproject>ollama-api-example</subproject>
        <subproject>rag-example</subproject>
        <subproject>tools-example</subproject>
    </subprojects>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.ai</groupId>
                <artifactId>spring-ai-bom</artifactId>
                <version>${spring-ai.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
