spring.ai.ollama.chat.options.model=qwen3:14b
spring.ai.ollama.embedding.options.model=qwen3-embedding:latest
spring.ai.ollama.chat.options.temperature=0.1
spring.autoconfigure.exclude[0]=org.springframework.ai.model.mistralai.autoconfigure.MistralAiChatAutoConfiguration
spring.autoconfigure.exclude[1]=org.springframework.ai.model.mistralai.autoconfigure.MistralAiEmbeddingAutoConfiguration
spring.autoconfigure.exclude[2]=org.springframework.ai.model.mistralai.autoconfigure.MistralAiModerationAutoConfiguration
