spring.ai.mistralai.api-key=${MISTRAL_AI_API_KEY}
spring.ai.mistralai.base-url=https://api.eu.mistral.ai
spring.ai.mistralai.chat.model=mistral-medium-latest
spring.ai.mistralai.chat.reasoning-effort=high
spring.ai.mistralai.chat.temperature=0.1
spring.ai.model.chat=mistral
