spring.application.name=chat-client-example
spring.main.web-application-type=none
spring.threads.virtual.enabled=true
spring.profiles.active=ollama
spring.ai.model.embedding=none
spring.ai.model.moderation=none
spring.ai.model.ocr=none
spring.ai.chat.memory.repository.jdbc.initialize-schema=always
arconia.dev.services.openlit.image-name=ghcr.io/openlit/openlit:2.1.0
arconia.dev.services.openlit.clickhouse-image-name=clickhouse/clickhouse-server:26.8-distroless
arconia.dev.services.postgresql.image-name=postgres:18.6
