spring.ai.mistralai.chat.options.model=magistral-medium-latest
spring.ai.mistralai.api-key=${MISTRAL_AI_API_KEY}
spring.ai.mistralai.chat.options.temperature=0.1
spring.autoconfigure.exclude[0]=org.springframework.ai.model.ollama.autoconfigure.OllamaApiAutoConfiguration
spring.autoconfigure.exclude[1]=org.springframework.ai.model.ollama.autoconfigure.OllamaChatAutoConfiguration
spring.autoconfigure.exclude[2]=org.springframework.ai.model.ollama.autoconfigure.OllamaEmbeddingAutoConfiguration
