spring.application.name=time-mcp-server
spring.threads.virtual.enabled=true
spring.ai.mcp.server.protocol=STATELESS
spring.ai.mcp.server.name=${spring.application.name}
spring.ai.mcp.server.instructions=This stateless server provides time tools.
server.port=8081
