services:
  postgres:
    image: 'postgres:18.4'
    environment:
      - 'POSTGRES_DB=rag_example'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=user'
    ports:
      - '5432'
  qdrant:
    image: 'qdrant/qdrant:v1.18.2'
    ports:
      - '6334'
