spring.application.name=tools-example
spring.main.web-application-type=none
spring.threads.virtual.enabled=true
spring.profiles.active=ollama
spring.ai.model.embedding=none
spring.ai.model.moderation=none
spring.ai.model.ocr=none
spring.ai.chat.memory.repository.jdbc.initialize-schema=always
arconia.dev.services.phoenix.image-name=arizephoenix/phoenix:version-20.12-nonroot
arconia.dev.services.postgresql.image-name=postgres:18.6
